ballet_waytoc_homepage:
    path:     /hello/{name}
    defaults: { _controller: BalletWaytocBundle:Default:index }

front_page:
    path:      /
    defaults:  { _controller: BalletWaytocBundle:Image:showImages }

post_image:
    path:     /item/{slug}
    defaults: { _controller: BalletWaytocBundle:Image:showImage }

about_page:
    path:      /about
    defaults:  { _controller: BalletWaytocBundle:Front:about  }

info_page:
    path:      /info
    defaults:  { _controller: BalletWaytocBundle:Front:info  }

prac:
    path: /prac
    defaults: {_controller: BalletWaytocBundle:Front:prac}

upload:
    path:   /upload
    defaults: {_controller: BalletWaytocBundle:Image:upload }


