ballet_waytoc_homepage:
    path:     /hello/{name}
    defaults: { _controller: BalletWaytocBundle:Default:index }

front_page:
    path:      /waytoc
    defaults:  { _controller: BalletWaytocBundle:Front:index }

about_page:
    path:      /about
    defaults:  { _controller: BalletWaytocBundle:Front:about  }

info_page:
    path:      /info
    defaults:  { _controller: BalletWaytocBundle:Front:info  }

prac:
    path: /prac
    defaults: {_controller: BalletWaytocBundle:Front:prac}

account_register:
    path:     /register
    defaults: { _controller: BalletWaytocBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: BalletWaytocBundle:Account:create }

