parameters:
#    ballet_waytoc.example.class: Ballet\WaytocBundle\Example

services:
#    ballet_waytoc.example:
#        class: %ballet_waytoc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
