ballet_post:
    resource: "@BalletPostBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ballet_waytoc:
    resource: "@BalletWaytocBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#_imagine:
#    resource: .
#    type:     imagine