user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ballet_waytoc:
    resource: "@BalletWaytocBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"