security:
    encoders:
        Ballet\WaytocBundle\Entity\User:
            algorithm: sha512
            iterations: 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database:
             entity: { class: BalletWaytocBundle:User, property: username }
        in_memory:
            memory:
                users:
                    ryan:
                        password: sha512
                        roles: 'ROLE_USER'
                    admin:
                        password: sha512
                        roles: 'ROLE_ADMIN'



    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /waytoc
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

#        secured_area:
#            pattern:   ^/login$
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login_check
#                username_parameter: _username
#                password_parameter: _password

    access_control:
          - { path: ^/about, roles: ROLE_USER }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }